import 'package:flutter/material.dart'
    show TextTheme, Colors, TextStyle, FontWeight;

const appTextTheme = TextTheme(
  headlineLarge: TextStyle(
    color: Colors.black,
    fontSize: 40.0,
    fontFamily: 'NunitoSans',
    letterSpacing: 1.0,
    fontWeight: FontWeight.w500,
  ),
  headlineMedium: TextStyle(
    color: Colors.black,
    fontSize: 32.0,
    fontFamily: 'NunitoSans',
    letterSpacing: 1.0,
    fontWeight: FontWeight.w500,
  ),
  headlineSmall: TextStyle(
    color: Colors.black,
    fontSize: 28.0,
    fontFamily: 'NunitoSans',
    letterSpacing: 1.0,
    fontWeight: FontWeight.w500,
  ),
  displayLarge: TextStyle(
    color: Colors.black,
    fontSize: 24.0,
    fontFamily: 'NunitoSans',
    letterSpacing: 1.0,
    fontWeight: FontWeight.w500,
  ),
  displayMedium: TextStyle(
    color: Colors.black,
    fontSize: 20.0,
    fontFamily: 'NunitoSans',
    letterSpacing: 1.0,
    fontWeight: FontWeight.w500,
  ),
  displaySmall: TextStyle(
    color: Colors.black,
    fontSize: 18.0,
    fontFamily: 'NunitoSans',
    letterSpacing: 1.0,
    fontWeight: FontWeight.w500,
  ),
  titleLarge: TextStyle(
    color: Colors.black,
    fontSize: 16.0,
    fontFamily: 'NunitoSans',
    letterSpacing: 1.0,
    fontWeight: FontWeight.w500,
  ),
  titleMedium: TextStyle(
    color: Colors.black,
    fontSize: 14.0,
    fontFamily: 'NunitoSans',
    letterSpacing: 1.0,
    fontWeight: FontWeight.w500,
  ),
  titleSmall: TextStyle(
    color: Colors.black,
    fontSize: 12.0,
    fontFamily: 'NunitoSans',
    letterSpacing: 1.0,
    fontWeight: FontWeight.w500,
  ),
  bodyLarge: TextStyle(
    color: Colors.black,
    fontSize: 16.0,
    fontFamily: 'NunitoSans',
    letterSpacing: 1.0,
    fontWeight: FontWeight.w400,
  ),
  bodyMedium: TextStyle(
    color: Colors.black,
    fontSize: 14.0,
    fontFamily: 'NunitoSans',
    letterSpacing: 1.0,
    fontWeight: FontWeight.w400,
  ),
  bodySmall: TextStyle(
    color: Colors.black,
    fontSize: 12.0,
    fontFamily: 'NunitoSans',
    letterSpacing: 1.0,
    fontWeight: FontWeight.w400,
  ),
  labelLarge: TextStyle(
    color: Colors.black,
    fontSize: 10.0,
    fontFamily: 'NunitoSans',
    letterSpacing: 1.0,
    fontWeight: FontWeight.w600,
  ),
  labelMedium: TextStyle(
    color: Colors.black,
    fontSize: 10.0,
    fontFamily: 'NunitoSans',
    letterSpacing: 1.0,
    fontWeight: FontWeight.w500,
  ),
  labelSmall: TextStyle(
    color: Colors.black,
    fontSize: 10.0,
    fontFamily: 'NunitoSans',
    letterSpacing: 1.0,
    fontWeight: FontWeight.w400,
  ),
);
